### ISSUE TITLE
newbie help request

### ISSUE THREAD

**Issue by agustin-jimenez** [WhyNotHugo/sysconfig#1]
Hi! Can I ask you **how it works? At high level**, obviously.

I'm found it interesting a lot and I want to build my own 'system dotfiles'. But **I didn't catch the workflow** of this repository.

Thank you in advanced!

**Comment by WhyNotHugo** [comment]
I use ArchLinux, which uses [`pacman`](https://wiki.archlinux.org/index.php/Pacman) as a package manager. Think things like `apt-get`, `yum` or `brew`.

The packages it handles are generated by a simple script called a [`PKGBUILD`](https://wiki.archlinux.org/index.php/PKGBUILD), and there's one in the root of this repository.

The `PKGBUILD` here, generates a package with all the files in the `etc` and `usr` directories in this repo. I just run `makepkg -i`, and that generates a package, and installs it.

The end result, is that all the files in `etc` and `usr` in this repository end up in my root filesystem, and belong to a specific package that tracks them (so if I tell my package manager which files belong to the package `sysconfig`, it'll list all these files. They don't sit there lost and forgotten forever.

This also lets me roll these files backwards/forwards in time.

When I [list orphan / dangling files](https://github.com/graysky2/lostfiles), these files that I've purposely put there are not included in that listing.

My mentality is that everything that's "installed" systemwide should be through a package manager -- so I can never accumulate orphan / dangling files, and can, eventually, figure out why a file is where it is. This introduces my config files into that. Keep in mind that I also avoid things like `sudo pip install` or `sudo npm install`. Using one package manager is perfect. Using two is a great recipe for breakage.

Additionally, there's also a `sysconfig.install` file. This file get _executed_ when I install the package.

Finally, some files are `hooks` that my package manager runs on certain events. For example, `usr/share/libalpm/hooks/99-drop-extra-en-dicts.hook` is run whenever the `hunspell-en_GB` package is installed. This package has English dictionaries, but it also includes lots of regional variants I don't want (they're like 20 and are listed when I pick a dictionary in, e.g.: Firefox). This hook deletes the files that other package installs.

Depending on how you see it, I've been running the same installation of Arch for about 10 years, and this is one of the things that keeps in sane (I've many times copied a full disk image from one machine to the next; it's hard to say if it's technically the same installation or not, but you get the point).

Hope this helps, cheers!

**Comment by agustin-jimenez** [comment]
You're awesome! Million thanks!

**Comment by WhyNotHugo** [comment]
Happy to help ^^
